In [1]:
from scipy.linalg import expm
from scipy.linalg import logm
import numpy as np
from math import *

import cv2

In [2]:
# 将向量转换为反对称矩阵 https://blog.csdn.net/weixin_44995665/article/details/102682666
def Skew(a):
    """
    得到了李代数对应的反对称矩阵
    got the corresponded antiSymmetric Matrix of the Lie algebra
    :param a:   Lie algebra 李代数
    :return:    antiSymmetric Matrix 反对称矩阵
    """
    
    a=a.ravel() #压缩为一维
    if len(a) == 3:
        A = np.array([[0, -a[2], a[1]],
                      [a[2], 0, -a[0]],
                      [-a[1], a[0], 0]])
        return A

    if len(a) == 2:
        A = np.array([a[1], -a[0]])
        return A
    exit(-1)

In [3]:
# 将向量转换为反对称矩阵
def InvSkew(A):
    V = np.array([A[2,1],A[0,2],A[1,0]])
    return V
    exit(-1)

In [4]:
# 李代数转李群
def so3ToSO3(xi):
    return expm(Skew(xi))

In [5]:
# 李群转李代数
tx=0*pi/4
ty=0*pi/6
tz=pi/2

Rx=np.array(
    [
        [1,     0,          0],
        [0,     cos(tx),    -sin(tx)],
        [0,     sin(tx),    cos(tx)]
    ])
Ry=np.array(
    [
        [cos(ty),   0,      sin(ty)  ],
        [0,         1,      0        ],
        [-sin(ty),  0,      cos(ty)  ]
    ])
Rz=np.array(
    [
        [cos(tz),   -sin(tz),   0],
        [sin(tz),   cos(tz),    0],
        [0,         0,          1]
    ])

R = Rz.dot(Ry.dot(Rx)) #生成三维旋转矩阵R,也即是李群

r = logm(R) #求矩阵的对数（正交矩阵的对数为对称矩阵）
aaa = InvSkew(r) #将对数矩阵转化为对应的向量
print(R)
print("aaa=")
print(aaa)

np.linalg.norm(aaa)

[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
aaa=
[0.         0.         1.57079633]


1.570796326794897

In [6]:
# 李代数转李群

M = expm(Skew(aaa)) #求李代数对应的李群
print("李群M=\r\n" + str(M))

#print("矩阵的迹trace=" + str(np.trace(M)))

#print("eig =" + str(np.linalg.eig(M)))

#print("theta")

#print(theta)
#a = aaa/theta
#print("a" + str(a))

李群M=
[[-4.50401187e-16 -1.00000000e+00 -0.00000000e+00]
 [ 1.00000000e+00 -4.50401187e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [7]:
#手写
print("aaa=" + str(aaa))
theta = np.linalg.norm(aaa)
print(theta)
a = aaa / theta
a.shape=(3,1)

print(a.shape)
print(np.cos(theta)*np.eye(3))
print(a.dot(a.T))
print(Skew(a))

b = np.cos(theta)*np.eye(3) + (1-np.cos(theta))*a.dot(a.T) + np.sin(theta)*Skew(a)
print(b)

aaa=[0.         0.         1.57079633]
1.570796326794897
(3, 1)
[[-3.8285687e-16 -0.0000000e+00 -0.0000000e+00]
 [-0.0000000e+00 -3.8285687e-16 -0.0000000e+00]
 [-0.0000000e+00 -0.0000000e+00 -3.8285687e-16]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
[[ 0. -1.  0.]
 [ 1.  0. -0.]
 [-0.  0.  0.]]
[[-3.8285687e-16 -1.0000000e+00  0.0000000e+00]
 [ 1.0000000e+00 -3.8285687e-16  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [8]:
#double theta = V.L2Norm();
#Matrix<double> n = new DenseMatrix(3, 1, (V / V.L2Norm()).ToArray());
#Matrix<double> R = Cos(theta) * DenseMatrix.CreateIdentity(3) + (1 - Cos(theta)) * n * n.Transpose() + Sin(theta) * Skew(n);


In [9]:
src = np.expand_dims(M, axis = -1)
print(src)
dst = np.zeros((3,3,1), np.uint8)
cv2.Rodrigues(src,dst)
print(M)
print(dst)

[[[-4.50401187e-16]
  [-1.00000000e+00]
  [-0.00000000e+00]]

 [[ 1.00000000e+00]
  [-4.50401187e-16]
  [ 0.00000000e+00]]

 [[ 0.00000000e+00]
  [ 0.00000000e+00]
  [ 1.00000000e+00]]]
[[-4.50401187e-16 -1.00000000e+00 -0.00000000e+00]
 [ 1.00000000e+00 -4.50401187e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[[0]
  [0]
  [0]]

 [[0]
  [0]
  [0]]

 [[0]
  [0]
  [0]]]


In [10]:
# SE3李群李代数映射

In [11]:
# 李群转李代数
tx=0*pi/4
ty=0*pi/6
tz=pi/2

Rx=np.array(
    [
        [1,     0,        0,        0],
        [0,     cos(tx),  -sin(tx), 0],
        [0,     sin(tx),  cos(tx),  0],
        [0,0,0,1]
    ])
Ry=np.array(
    [
        [cos(ty),   0,      sin(ty),0  ],
        [0,         1,      0      ,0  ],
        [-sin(ty),  0,      cos(ty),0  ],
        [0,0,0,1]
    ])
Rz=np.array(
    [
        [cos(tz),   -sin(tz),   0,0],
        [sin(tz),   cos(tz),    0,0],
        [0,         0,          1,0],
        [0,0,0,1]
    ])
P=np.array(
    [
        [1, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])
T =P.dot(Rz.dot(Ry.dot(Rx)))#生成三维旋转矩阵R,也即是李群e
print(T)

[[ 6.123234e-17 -1.000000e+00  0.000000e+00  1.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


In [12]:
# 欧式群转李代数
R=T[0:3,0:3]
t=T[0:3,3:4]
theta=np.arccos((np.trace(R)-1)/2)
eigvalue,eigvector=np.linalg.eig(R)
index=eigvalue.argmax()

a=eigvector[:,index:index+1]
a=np.real(a)

J = (np.sin(theta)/theta)*np.eye(3) + (1 - np.sin(theta)/theta) * a.dot(a.T) + (1-np.cos(theta))/theta*Skew(a)
rho = np.linalg.inv(J).dot(t)
phi = theta * a

ksi = np.vstack((rho,phi))
print(ksi)

[[ 0.78539816]
 [-0.78539816]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 1.57079633]]


In [13]:
# 李代数转欧式群
rho=ksi[0:3,0:1]
phi=ksi[3:7,0:1]
print(phi)
theta=np.linalg.norm(phi)
a=phi/theta

J = (np.sin(theta)/theta)*np.eye(3) + (1 - np.sin(theta)/theta) * a.dot(a.T) + (1-np.cos(theta))/theta*Skew(a)
J.dot(rho)


M = expm(Skew(phi)) #求李代数对应的李群
print("李群M=\r\n" + str(M))

[[0.        ]
 [0.        ]
 [1.57079633]]
李群M=
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
