In [1]:
from scipy.linalg import expm
from scipy.linalg import logm
import numpy as np
from math import *

In [2]:
# 将向量转换为反对称矩阵 https://blog.csdn.net/weixin_44995665/article/details/102682666
def SkewFun(a):
    """
    得到了李代数对应的反对称矩阵
    got the corresponded antiSymmetric Matrix of the Lie algebra
    :param a:   Lie algebra 李代数
    :return:    antiSymmetric Matrix 反对称矩阵
    """
    if len(a) == 3:
        A = np.array([[0, -a[2], a[1]],
                      [a[2], 0, -a[0]],
                      [-a[1], a[0], 0]])
        return A

    if len(a) == 2:
        A = np.array([a[1], -a[0]])
        return A
    exit(-1)

In [3]:
# 将向量转换为反对称矩阵
def InvSkewFun(A):
    V = np.array([A[2,1],A[0,2],A[1,0]])
    return V
    exit(-1)

In [4]:
# 李代数转李群
def so3ToSO3(xi):
    return expm(SkewFun(xi))

In [5]:
# 李群转李代数
tx=0
ty=0
tz=pi/2

Rx=np.array(
    [
        [1,     0,          0],
        [0,     cos(tx),    -sin(tx)],
        [0,     sin(tx),    cos(tx)]
    ])
Ry=np.array(
    [
        [cos(ty),   0,      sin(ty)  ],
        [0,         1,      0        ],
        [-sin(ty),  0,      cos(ty)  ]
    ])
Rz=np.array(
    [
        [cos(tz),   -sin(tz),   0],
        [sin(tz),   cos(tz),    0],
        [0,         0,          1]
    ])

R = Rz.dot(Ry.dot(Rx))

r = logm(R)
aaa = InvSkewFun(r)
print(R)
print("aaa=")
print(aaa)

np.linalg.norm(aaa)

[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
aaa=
[0.         0.         1.57079633]


1.570796326794897

In [6]:
# 李代数转李群
aaa[2]=0.001
M = expm(SkewFun(aaa))
#M = expm(SkewFun([2,2,2]))
print(M)

print("trace=")
print(np.trace(M))

print("eig =")
np.linalg.eig(M)

print("theta")
theta=np.linalg.norm(aaa)
print(theta)
a=aaa/theta
print(a)

np.cos(theta)*np.eye(3) + (1-np.cos(theta))*a.T.dot(a) + np.sin(theta)*SkewFun(a)

[[ 9.99999500e-01 -9.99999833e-04  0.00000000e+00]
 [ 9.99999833e-04  9.99999500e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
trace=
2.9999990000000833
eig =
theta
0.001
[0. 0. 1.]


array([[ 1.00000000e+00, -9.99499833e-04,  4.99999958e-07],
       [ 1.00049983e-03,  1.00000000e+00,  4.99999958e-07],
       [ 4.99999958e-07,  4.99999958e-07,  1.00000000e+00]])

In [7]:
print(aaa)
print(SkewFun(aaa))
print(expm(SkewFun(aaa)))

print("总结：\r\n正交矩阵取矩阵对数得到的结果为反对称矩阵，而反对称矩阵与向量一一对应，因此正交矩阵与向量可得到一对一的映射")

[0.    0.    0.001]
[[ 0.    -0.001  0.   ]
 [ 0.001  0.    -0.   ]
 [-0.     0.     0.   ]]
[[ 9.99999500e-01 -9.99999833e-04  0.00000000e+00]
 [ 9.99999833e-04  9.99999500e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
总结：
正交矩阵取矩阵对数得到的结果为反对称矩阵，而反对称矩阵与向量一一对应，因此正交矩阵与向量可得到一对一的映射


In [8]:
SkewFun([1,0,0])

array([[ 0,  0,  0],
       [ 0,  0, -1],
       [ 0,  1,  0]])

In [10]:
R = Rz.dot((Ry.dot(Rx)))
t = np.array([[1],[0],[0]])
P = np.hstack((R, t))
P = np.vstack((P,[[0,0,0,1]]))
print(P)

(np.trace(R)-1)/2

[[ 6.123234e-17 -1.000000e+00  0.000000e+00  1.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


1.1102230246251565e-16